name: Go IPS2Crash Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Check if tag is part of main branch
        run: |
          git fetch --all --tags
          git checkout ${{ github.ref }}
          TAG_COMMIT_HASH=$(git rev-parse HEAD)
          MAIN_BRANCH_COMMIT_HASH=$(git rev-parse origin/main)
          if git merge-base --is-ancestor $TAG_COMMIT_HASH $MAIN_BRANCH_COMMIT_HASH; then
            echo "Tag is part of main branch."
          else
            echo "Tag is not part of main branch. Exiting."
            exit 1
          fi
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
