name: Go IPS2Crash Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Exit if not on master branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
